.TH EX3 "FEBRUARY 2019" Console Debugging "Exercise 3"
.SH Name
.B Harsh Patel
.SH Descriptions
.B Part 2:
Upon looking at the source code, this is a rock, paper, scissors program. The error is caused on line 112 because it is pointing to memory that doesn't exist. No memory was allocated to hold the value, instead it was initialized as a null and could not dereference.

.B Part 3:
This program adds A and B and stores it in C. The final values of the int variables are: a = 30, b = 7, and c = 37.
